## Trials here

In [115]:
%load_ext autoreload
%autoreload 2
import vcf
import population
import pandas as pd
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [116]:
pop = population.Population()

In [117]:
len(pop)

0

In [118]:
pop.extract_unlabeled()

In [ ]:
pop.load_from_vcf(filename='data/final.recode.vcf', printinfo=True, maxval=1000, keep_prev=False)

having 84 chromosomes
meta :
OrderedDict([('fileformat', 'VCFv4.2'), ('hailversion', ['devel-76c42fe'])])
genomesize : 
3101804739
 oing chrom : 1, at pos : 41285591 ,number : 999
PHASE nonzero 22688
SNPs nonzero 230056
you have 210 non finish europeanin your labeled set
you have 0 unknownin your labeled set
you have 228 south asianin your labeled set
you have 253 east asianin your labeled set
you have 155 mixed americanin your labeled set
you have 58 finishin your labeled set
you have 382 africanin your labeled set


In [ ]:
pop.load_from_vcf(filename='data/final.recode.vcf', printinfo=True, maxval=3000, keep_prev=True)

having 84 chromosomes
meta :
OrderedDict([('fileformat', 'VCFv4.2'), ('hailversion', ['devel-76c42fe'])])
genomesize : 
3101804739


In [ ]:
pop.test_gt.shape

In [99]:
pop.reduce_features(n_components=400,val='gt',reducer='pca')

In [101]:
pop.train_classifier(classifier='gaussian')

cv scores : [0.52204176 0.56308411 0.51522248]
the total score is of 0.5334494526420658


0.5334494526420658

In [102]:
pop['MacArthurLab_17']

non finish european


In [68]:
pop.reduce_features(n_components=400,val='gt',reducer='kpca')

In [64]:
pop.train_classifier(classifier='knn')

2       eas
4       eas
6       nfe
7       nfe
8       nfe
9       nfe
11      nfe
12      nfe
13      nfe
15      nfe
16      nfe
19      nfe
22      nfe
24      nfe
28      nfe
29      nfe
30      nfe
33      nfe
34      nfe
38      nfe
40      nfe
42      nfe
43      nfe
44      nfe
45      nfe
46      nfe
47      nfe
48      nfe
50      nfe
51      nfe
       ... 
1909    nfe
1910    nfe
1911    nfe
1915    sas
1916    sas
1917    sas
1919    sas
1920    sas
1922    sas
1924    sas
1926    sas
1927    sas
1928    sas
1929    sas
1930    sas
1932    sas
1934    sas
1937    sas
1940    sas
1943    sas
1946    sas
1947    sas
1948    sas
1949    sas
1950    sas
1951    sas
1953    sas
1955    sas
1959    sas
1963    sas
Name: ancestry, Length: 1286, dtype: object

In [92]:
pop.reduce_features(n_components=300,val='gt',reducer='spca')

In [93]:
pop.train_classifier(classifier='knn')

array([0.85150812, 0.9088785 , 0.92037471])

In [72]:
pop.reduce_features(n_components=400,val='gt',reducer='lda')

[autoreload of src failed: Traceback (most recent call last):
  File "/Users/jeremie/anaconda2/envs/tensorflow1/lib/python2.7/site-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
  File "src.py", line 186
    elif self.rec[record.CHROM][]
       ^
IndentationError: expected an indented block
]


In [73]:
pop.train_classifier(classifier='knn')

array([0.49074074, 0.21671827, 0.21875   , 0.35736677])

In [37]:
pop.reduce_features(n_components=400,val='pha',reducer='pca')

array([[1, 1, 1, 1],
       [4, 2, 2, 2],
       [3, 3, 2, 1],
       [4, 2, 4, 4]])

In [83]:
pop.train_classifier(classifier='knn')

kernel_task
launchd
syslogd
UserEventAgent
uninstalld
kextd
fseventsd
appleeventsd
systemstats
configd
powerd
logd
warmd
mds
diskarbitrationd
Installer Progre
backupd-helper
AGSService
opendirectoryd
apsd
nbstated
launchservicesd
securityd
usbmuxd
locationd
autofsd
displaypolicyd
dasd
kdc
loginwindow
logind
revisiond
KernelEventAgent
bluetoothd
com.torrents-tim
hidd
corebrightnessd
AirPlayXPCHelper
taskgated
notifyd
distnoted
cfprefsd
authd
coreservicesd
com.apple.ctkpcs
coreaudiod
WindowServer
mDNSResponder
mDNSResponderHel
awacsd
airportd
apfsd
signpost_notific
sysmond
systemstats
symptomsd
AppleCameraAssis
lsd
syspolicyd
watchdogd
thermald
mds_stores
CVMServer
sharedfilelistd
fontd
securityd_servic
com.apple.Ambien
cfprefsd
distnoted
trustd
com.apple.speech
UserEventAgent
lsd
languageassetd
identityservicesd
imagent
wirelessproxd
rapportd
usernoted
CrashReporterSup
NotificationCenter
sharingd
WiFiAgent
useractivityd
mediaremoteagent
cupsd
sharedfilelistd
SubmitDiagInfo
filecoordinat

In [96]:
pop.reduce_features(n_components=400,val='gt',reducer='pca')

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [106]:
pop.train_classifier(classifier='svm')

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([], shape=(0, 4), dtype=float64),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [120]:
pop.predic

210

In [129]:
list(labeled.loc[labeled['sample_id'] == 'MacArthurLab_9']['ancestry'])[0]

'nfe'

In [22]:
import numpy as np
a = range(30)

In [23]:
b = range(30)

In [35]:
a = np.vstack((a,a))

In [36]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  

In [104]:
a = pd.concat([pop.labeled, pop.tofind])

In [114]:
for key in pop.keys():
    pop[key]

east asian
east asian
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
finish
finish
finish
finish
finish
finish
finish
finish
finish
finish
finish
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
non finish european
n

african
african
african
african
african
african
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
south asian
sout

KeyError: nan

In [ ]:
pop.found