## Trials here

In [1]:
%load_ext autoreload
%autoreload 2
import vcf
import src
import pandas as pd
import numpy as np

In [2]:
vcf_reader = vcf.Reader(open('data/trial1.recode.vcf', 'r'))
tofind,labeled = src.sortval()

In [50]:
names = list(labeled['sample_id'])
rec = {}
gt = []
pha = []
chrom = -1
for i, record in enumerate(vcf_reader):
    gt.append([])
    pha.append([])
    print "doing chrom,pos : " + str(record.CHROM) + ',' + str(record.POS) + "\r",
    if record.CHROM != chrom:
        chrom = record.CHROM
        rec.update({chrom: []})
    rec[chrom].append([record.POS, record.REF, record.ALT])
    for name in names:
        
        gt[i].append(record.genotype(name).gt_type if record.genotype(name).gt_type is not None else 0)
        pha[i].append(record.genotype(name).phased if record.genotype(name).phased is not None else 0)
    if i > 8000:
        break

In [51]:
pha = np.array(pha, dtype=np.bool).T
gt = np.array(gt).T

[autoreload of src failed: Traceback (most recent call last):
  File "/Users/jeremie/anaconda2/envs/tensorflow1/lib/python2.7/site-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
  File "src.py", line 198
    elif self.rec[record.CHROM][]
       ^
IndentationError: expected an indented block
]


In [52]:
np.count_nonzero(pha)

173071

In [53]:
np.count_nonzero(gt)

2618298

In [34]:
contigs = list(vcf_reader.contigs.keys())

In [35]:
contigs

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 'X',
 'Y',
 'MT',
 'GL000207.1',
 'GL000226.1',
 'GL000229.1',
 'GL000231.1',
 'GL000210.1',
 'GL000239.1',
 'GL000235.1',
 'GL000201.1',
 'GL000247.1',
 'GL000245.1',
 'GL000197.1',
 'GL000203.1',
 'GL000246.1',
 'GL000249.1',
 'GL000196.1',
 'GL000248.1',
 'GL000244.1',
 'GL000238.1',
 'GL000202.1',
 'GL000234.1',
 'GL000232.1',
 'GL000206.1',
 'GL000240.1',
 'GL000236.1',
 'GL000241.1',
 'GL000243.1',
 'GL000242.1',
 'GL000230.1',
 'GL000237.1',
 'GL000233.1',
 'GL000204.1',
 'GL000198.1',
 'GL000208.1',
 'GL000191.1',
 'GL000227.1',
 'GL000228.1',
 'GL000214.1',
 'GL000221.1',
 'GL000209.1',
 'GL000218.1',
 'GL000220.1',
 'GL000213.1',
 'GL000211.1',
 'GL000199.1',
 'GL000217.1',
 'GL000216.1',
 'GL000215.1',
 'GL000205.1',
 'GL000219.1',
 'GL000224.1',
 'GL000223.1',
 'GL000195.1',
 'GL000212.1',
 'GL000222.1',
 'GL000200.1',
 'GL000193.

In [21]:
gt

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [89]:
from sklearn.decomposition import PCA
pca = PCA(n_components=100)
redgt = pca.fit_transform(gt)

In [90]:
redgt.shape

(1286, 100)

In [91]:
Y = labeled['ancestry']

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(redgt, Y, test_size=0.2)

2       eas
4       eas
6       nfe
7       nfe
8       nfe
9       nfe
11      nfe
12      nfe
13      nfe
15      nfe
16      nfe
19      nfe
22      nfe
24      nfe
28      nfe
29      nfe
30      nfe
33      nfe
34      nfe
38      nfe
40      nfe
42      nfe
43      nfe
44      nfe
45      nfe
46      nfe
47      nfe
48      nfe
50      nfe
51      nfe
       ... 
1909    nfe
1910    nfe
1911    nfe
1915    sas
1916    sas
1917    sas
1919    sas
1920    sas
1922    sas
1924    sas
1926    sas
1927    sas
1928    sas
1929    sas
1930    sas
1932    sas
1934    sas
1937    sas
1940    sas
1943    sas
1946    sas
1947    sas
1948    sas
1949    sas
1950    sas
1951    sas
1953    sas
1955    sas
1959    sas
1963    sas
Name: ancestry, Length: 1286, dtype: object

In [92]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors.nearest_centroid import NearestCentroid
clf = NearestCentroid()

In [93]:
cross_val_score(clf, redgt, Y, scoring='accuracy',cv=3,n_jobs=1) 

array([0.85150812, 0.9088785 , 0.92037471])

In [72]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)

[autoreload of src failed: Traceback (most recent call last):
  File "/Users/jeremie/anaconda2/envs/tensorflow1/lib/python2.7/site-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
  File "src.py", line 186
    elif self.rec[record.CHROM][]
       ^
IndentationError: expected an indented block
]


In [73]:
cross_val_score(clf, redgt, Y, scoring='accuracy',cv=4,n_jobs=1) 

array([0.49074074, 0.21671827, 0.21875   , 0.35736677])

In [37]:
A.T

array([[1, 1, 1, 1],
       [4, 2, 2, 2],
       [3, 3, 2, 1],
       [4, 2, 4, 4]])

In [83]:
import psutil
for p in psutil.process_iter():
    try:
        print p.name()
    except (psutil.AccessDenied, psutil.ZombieProcess):
        pass
    except psutil.NoSuchProcess:
        continue

kernel_task
launchd
syslogd
UserEventAgent
uninstalld
kextd
fseventsd
appleeventsd
systemstats
configd
powerd
logd
warmd
mds
diskarbitrationd
Installer Progre
backupd-helper
AGSService
opendirectoryd
apsd
nbstated
launchservicesd
securityd
usbmuxd
locationd
autofsd
displaypolicyd
dasd
kdc
loginwindow
logind
revisiond
KernelEventAgent
bluetoothd
com.torrents-tim
hidd
corebrightnessd
AirPlayXPCHelper
taskgated
notifyd
distnoted
cfprefsd
authd
coreservicesd
com.apple.ctkpcs
coreaudiod
WindowServer
mDNSResponder
mDNSResponderHel
awacsd
airportd
apfsd
signpost_notific
sysmond
systemstats
symptomsd
AppleCameraAssis
lsd
syspolicyd
watchdogd
thermald
mds_stores
CVMServer
sharedfilelistd
fontd
securityd_servic
com.apple.Ambien
cfprefsd
distnoted
trustd
com.apple.speech
UserEventAgent
lsd
languageassetd
identityservicesd
imagent
wirelessproxd
rapportd
usernoted
CrashReporterSup
NotificationCenter
sharingd
WiFiAgent
useractivityd
mediaremoteagent
cupsd
sharedfilelistd
SubmitDiagInfo
filecoordinat

In [96]:
 x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [106]:
np.vsplit(x, np.array((3,2)))

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([], shape=(0, 4), dtype=float64),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [120]:
labeled.loc[labeled['ancestry'] == 'nfe'].shape[0]

210

In [129]:
list(labeled.loc[labeled['sample_id'] == 'MacArthurLab_9']['ancestry'])[0]

'nfe'